version: "3"

services:
  roboto-web:
    build: .
    volumes:
      - ./src/roboto:/code/roboto
    working_dir: /code
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    command: >
      /bin/bash -c "source activate roboto-env && uvicorn --reload --host 0.0.0.0 --port 8001 roboto.app.main:app"
    restart: on-failure
