name: roboto-env
channels:
  - conda-forge
  - defaults
dependencies:
  - fastapi >=0.68.0
  - fastapi_utils
  - pydantic >=1.8.0
  - uvicorn >=0.15.0
  - grayskull >=1.1.0
  - conda-build
  - requests
  - git
